name: Test

on:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      # - name: Lint markdown
      #   run: npm run lint:markdown
      
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install packages
        run: npm ci

      - name: Type checks
        run: npm run type-check

      - name: Test Insomnium
        working-directory: packages/insomnia
        run: npm test
        if: always() # Run this even if the previous step already failed the run

      - name: Test Insomnium Testing
        working-directory: packages/insomnia-testing
        run: npm test
        if: always() # Run this even if the previous step already failed the run

      # - name: Build app for smoke tests
      #   run: NODE_OPTIONS='--max_old_space_size=6144' npm run app-build

      # - name: Smoke test electron app
      #   # Partial Smoke test run, for regular CI triggers
      #   if: ${{ !startsWith(github.head_ref, 'release/') }}
      #   run: npm run test:build -w packages/insomnia-smoke-test -- --project=Smoke

      # - name: Prerelease test electron app
      #   # Full Smoke test run, for Release PRs
      #   if: ${{ startsWith(github.head_ref, 'release/') }}
      #   run: npm run test:build -w packages/insomnia-smoke-test -- --project=Default

      # # 

      # - name: Upload smoke test traces
      #   uses: actions/upload-artifact@v3
      #   with:
      #     if-no-files-found: ignore
      #     name: ubuntu-smoke-test-traces-${{ github.run_number }}
      #     path: packages/insomnia-smoke-test/traces
